
/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftListViewBinding$Listener ///

package org.swiftjava.com_johnholdsworth;

@SuppressWarnings("JniMissingFunction")
public class SwiftListViewBinding_ListenerProxy implements com.johnholdsworth.swiftbindings.SwiftListViewBinding.Listener {

    // address of proxy object
    long __swiftObject;

    SwiftListViewBinding_ListenerProxy( long __swiftObject ) {
        this.__swiftObject = __swiftObject;
    }

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftListViewBinding$Listener.configureCell(com.johnholdsworth.swiftbindings.SwiftListViewBinding$Cell,int)

    public native void __configureCell( long __swiftObject, com.johnholdsworth.swiftbindings.SwiftListViewBinding.Cell cell, int row );

    public void configureCell( com.johnholdsworth.swiftbindings.SwiftListViewBinding.Cell cell, int row ) {
        __configureCell( __swiftObject, cell, row );
    }

    /// public abstract int com.johnholdsworth.swiftbindings.SwiftListViewBinding$Listener.numberOfRows()

    public native int __numberOfRows( long __swiftObject );

    public int numberOfRows() {
        return __numberOfRows( __swiftObject  );
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
