
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$GATTAttribute ///

public protocol SwiftBluetoothBinding_GATTAttribute: JavaProtocol {

    /// public abstract java.lang.String com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$GATTAttribute.getUUID()

    func getUUID() -> String!

}


open class SwiftBluetoothBinding_GATTAttributeForward: JNIObjectForward, SwiftBluetoothBinding_GATTAttribute {

    private static var SwiftBluetoothBinding_GATTAttributeJNIClass: jclass?

    /// public abstract java.lang.String com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$GATTAttribute.getUUID()

    private static var getUUID_MethodID_2: jmethodID?

    open func getUUID() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getUUID", methodSig: "()Ljava/lang/String;", methodCache: &SwiftBluetoothBinding_GATTAttributeForward.getUUID_MethodID_2, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


}

