
import java_swift
import java_util

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral$Responder ///

public protocol SwiftBluetoothBinding_Peripheral_Responder: JavaProtocol {

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral$Responder.close()

    func close()

    /// public abstract java.util.List com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral$Responder.getServices()

    func getServices() -> java_util.List!

    /// public abstract boolean com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral$Responder.refresh()

    func refresh() -> Bool

}


open class SwiftBluetoothBinding_Peripheral_ResponderForward: JNIObjectForward, SwiftBluetoothBinding_Peripheral_Responder {

    private static var SwiftBluetoothBinding_Peripheral_ResponderJNIClass: jclass?

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral$Responder.close()

    private static var close_MethodID_4: jmethodID?

    open func close() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "close", methodSig: "()V", methodCache: &SwiftBluetoothBinding_Peripheral_ResponderForward.close_MethodID_4, args: &__args, locals: &__locals )
    }


    /// public abstract java.util.List com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral$Responder.getServices()

    private static var getServices_MethodID_5: jmethodID?

    open func getServices() -> java_util.List! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getServices", methodSig: "()Ljava/util/List;", methodCache: &SwiftBluetoothBinding_Peripheral_ResponderForward.getServices_MethodID_5, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_util.ListForward( javaObject: __return ) : nil
    }


    /// public abstract boolean com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral$Responder.refresh()

    private static var refresh_MethodID_6: jmethodID?

    open func refresh() -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "refresh", methodSig: "()Z", methodCache: &SwiftBluetoothBinding_Peripheral_ResponderForward.refresh_MethodID_6, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }


}

