
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftMathBinding ///

public protocol SwiftMathBinding: JavaProtocol {

}


open class SwiftMathBindingForward: JNIObjectForward, SwiftMathBinding {

    private static var SwiftMathBindingJNIClass: jclass?

}

