
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftActivityBinding$Responder ///

public protocol SwiftActivityBinding_Responder: JavaProtocol {

}


open class SwiftActivityBinding_ResponderForward: JNIObjectForward, SwiftActivityBinding_Responder {

    private static var SwiftActivityBinding_ResponderJNIClass: jclass?

}

