
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$GATTService ///

public protocol SwiftBluetoothBinding_GATTService: JavaProtocol {

}


open class SwiftBluetoothBinding_GATTServiceForward: JNIObjectForward, SwiftBluetoothBinding_GATTService {

    private static var SwiftBluetoothBinding_GATTServiceJNIClass: jclass?

}

