
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftListViewBinding$Listener ///

public protocol SwiftListViewBinding_Listener: JavaProtocol {

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftListViewBinding$Listener.configureCell(com.johnholdsworth.swiftbindings.SwiftListViewBinding$Cell,int)

    func configureCell( cell: SwiftListViewBinding_Cell?, row: Int )

    /// public abstract int com.johnholdsworth.swiftbindings.SwiftListViewBinding$Listener.numberOfRows()

    func numberOfRows() -> Int

}


open class SwiftListViewBinding_ListenerForward: JNIObjectForward, SwiftListViewBinding_Listener {

    private static var SwiftListViewBinding_ListenerJNIClass: jclass?

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftListViewBinding$Listener.configureCell(com.johnholdsworth.swiftbindings.SwiftListViewBinding$Cell,int)

    private static var configureCell_MethodID_3: jmethodID?

    open func configureCell( cell: SwiftListViewBinding_Cell?, row: Int ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = JNIType.toJava( value: cell, locals: &__locals )
        __args[1] = jvalue( i: jint(row) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "configureCell", methodSig: "(Lcom/johnholdsworth/swiftbindings/SwiftListViewBinding$Cell;I)V", methodCache: &SwiftListViewBinding_ListenerForward.configureCell_MethodID_3, args: &__args, locals: &__locals )
    }

    open func configureCell( _ _cell: SwiftListViewBinding_Cell?, _ _row: Int ) {
        configureCell( cell: _cell, row: _row )
    }

    /// public abstract int com.johnholdsworth.swiftbindings.SwiftListViewBinding$Listener.numberOfRows()

    private static var numberOfRows_MethodID_4: jmethodID?

    open func numberOfRows() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "numberOfRows", methodSig: "()I", methodCache: &SwiftListViewBinding_ListenerForward.numberOfRows_MethodID_4, args: &__args, locals: &__locals )
        return Int(__return)
    }


}

private typealias SwiftListViewBinding_Listener_configureCell_0_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong, _: jobject?, _: jint ) -> ()

private func SwiftListViewBinding_Listener_configureCell_0( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong, _ cell: jobject?, _ row: jint ) -> () {
    SwiftListViewBinding_ListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).configureCell( cell: cell != nil ? SwiftListViewBinding_CellForward( javaObject: cell ) : nil, row: Int(row) )
}

private typealias SwiftListViewBinding_Listener_numberOfRows_1_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong ) -> jint

private func SwiftListViewBinding_Listener_numberOfRows_1( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong ) -> jint {
    let __return = SwiftListViewBinding_ListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).numberOfRows( )
    var __locals = [jobject]()
    return JNI.check( jvalue( i: jint(__return) ).i, &__locals, removeLast: true )
}

fileprivate class SwiftListViewBinding_ListenerLocal_: JNILocalProxy<SwiftListViewBinding_Listener, Any> {

    fileprivate static let _proxyClass: jclass = {
        var natives = [JNINativeMethod]()

        let SwiftListViewBinding_Listener_configureCell_0_thunk: SwiftListViewBinding_Listener_configureCell_0_type = SwiftListViewBinding_Listener_configureCell_0
        natives.append( JNINativeMethod( name: strdup("__configureCell"), signature: strdup("(JLcom/johnholdsworth/swiftbindings/SwiftListViewBinding$Cell;I)V"), fnPtr: unsafeBitCast( SwiftListViewBinding_Listener_configureCell_0_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let SwiftListViewBinding_Listener_numberOfRows_1_thunk: SwiftListViewBinding_Listener_numberOfRows_1_type = SwiftListViewBinding_Listener_numberOfRows_1
        natives.append( JNINativeMethod( name: strdup("__numberOfRows"), signature: strdup("(J)I"), fnPtr: unsafeBitCast( SwiftListViewBinding_Listener_numberOfRows_1_thunk, to: UnsafeMutableRawPointer.self ) ) )

        natives.append( JNINativeMethod( name: strdup("__finalize"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( JNIReleasableProxy__finalize_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let clazz = JNI.FindClass( proxyClassName() )
        withUnsafePointer(to: &natives[0]) {
            nativesPtr in
            if JNI.api.RegisterNatives( JNI.env, clazz, nativesPtr, jint(natives.count) ) != jint(JNI_OK) {
                JNI.report( "Unable to register java natives" )
            }
        }

        defer { JNI.DeleteLocalRef( clazz ) }
        return JNI.api.NewGlobalRef( JNI.env, clazz )!
    }()

    override open class func proxyClassName() -> String { return "org/swiftjava/com_johnholdsworth/SwiftListViewBinding_ListenerProxy" }
    override open class func proxyClass() -> jclass? { return _proxyClass }

}

extension SwiftListViewBinding_Listener {

    public func localJavaObject( _ locals: UnsafeMutablePointer<[jobject]> ) -> jobject? {
        return SwiftListViewBinding_ListenerLocal_( owned: self, proto: self ).localJavaObject( locals )
    }

}

open class SwiftListViewBinding_ListenerBase: SwiftListViewBinding_Listener {

    public init() {}

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftListViewBinding$Listener.configureCell(com.johnholdsworth.swiftbindings.SwiftListViewBinding$Cell,int)

    open func configureCell( cell: SwiftListViewBinding_Cell?, row: Int ) /**/ {
    }


    /// public abstract int com.johnholdsworth.swiftbindings.SwiftListViewBinding$Listener.numberOfRows()

    open func numberOfRows() -> Int /**/ {
        return 0
    }


}
