
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftAdapterBinding ///

public protocol SwiftAdapterBinding: JavaProtocol {

}


open class SwiftAdapterBindingForward: JNIObjectForward, SwiftAdapterBinding {

    private static var SwiftAdapterBindingJNIClass: jclass?

}

