
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftMathBinding$Responder ///

public protocol SwiftMathBinding_Responder: JavaProtocol {

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftMathBinding$Responder.processedSum(int)

    func processedSum( result: Int )

}


open class SwiftMathBinding_ResponderForward: JNIObjectForward, SwiftMathBinding_Responder {

    private static var SwiftMathBinding_ResponderJNIClass: jclass?

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftMathBinding$Responder.processedSum(int)

    private static var processedSum_MethodID_2: jmethodID?

    open func processedSum( result: Int ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = jvalue( i: jint(result) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "processedSum", methodSig: "(I)V", methodCache: &SwiftMathBinding_ResponderForward.processedSum_MethodID_2, args: &__args, locals: &__locals )
    }

    open func processedSum( _ _result: Int ) {
        processedSum( result: _result )
    }

}

