
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$GATTService ///

public protocol SwiftBluetoothBinding_GATTService: SwiftBluetoothBinding_GATTAttribute {

}


open class SwiftBluetoothBinding_GATTServiceForward: SwiftBluetoothBinding_GATTAttributeForward, SwiftBluetoothBinding_GATTService {

    private static var SwiftBluetoothBinding_GATTServiceJNIClass: jclass?

}

