
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$GATTCharacteristic ///

public protocol SwiftBluetoothBinding_GATTCharacteristic: SwiftBluetoothBinding_GATTAttribute {

}


open class SwiftBluetoothBinding_GATTCharacteristicForward: SwiftBluetoothBinding_GATTAttributeForward, SwiftBluetoothBinding_GATTCharacteristic {

    private static var SwiftBluetoothBinding_GATTCharacteristicJNIClass: jclass?

}

