
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftListViewBinding$Responder ///

public protocol SwiftListViewBinding_Responder: JavaProtocol {

}


open class SwiftListViewBinding_ResponderForward: JNIObjectForward, SwiftListViewBinding_Responder {

    private static var SwiftListViewBinding_ResponderJNIClass: jclass?

}

