
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral ///

public protocol SwiftBluetoothBinding_Peripheral: JavaProtocol {

    /// public abstract com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$BluetoothDevice com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral.getDevice()

    func getDevice() -> SwiftBluetoothBinding_BluetoothDevice!

}


open class SwiftBluetoothBinding_PeripheralForward: JNIObjectForward, SwiftBluetoothBinding_Peripheral {

    private static var SwiftBluetoothBinding_PeripheralJNIClass: jclass?

    /// public abstract com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$BluetoothDevice com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral.getDevice()

    private static var getDevice_MethodID_2: jmethodID?

    open func getDevice() -> SwiftBluetoothBinding_BluetoothDevice! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getDevice", methodSig: "()Lcom/johnholdsworth/swiftbindings/SwiftBluetoothBinding$BluetoothDevice;", methodCache: &SwiftBluetoothBinding_PeripheralForward.getDevice_MethodID_2, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? SwiftBluetoothBinding_BluetoothDeviceForward( javaObject: __return ) : nil
    }


}

