
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$GATTDescriptor ///

public protocol SwiftBluetoothBinding_GATTDescriptor: JavaProtocol {

}


open class SwiftBluetoothBinding_GATTDescriptorForward: JNIObjectForward, SwiftBluetoothBinding_GATTDescriptor {

    private static var SwiftBluetoothBinding_GATTDescriptorJNIClass: jclass?

}

