
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftAdapterBinding$Cell ///

public protocol SwiftAdapterBinding_Cell: JavaProtocol {

}


open class SwiftAdapterBinding_CellForward: JNIObjectForward, SwiftAdapterBinding_Cell {

    private static var SwiftAdapterBinding_CellJNIClass: jclass?

}

