
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanRecord ///

public protocol SwiftBluetoothBinding_ScanRecord: JavaProtocol {

}


open class SwiftBluetoothBinding_ScanRecordForward: JNIObjectForward, SwiftBluetoothBinding_ScanRecord {

    private static var SwiftBluetoothBinding_ScanRecordJNIClass: jclass?

}

