
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothScannerActivityBinding$Responder ///

public protocol SwiftBluetoothScannerActivityBinding_Responder: SwiftActivityBinding_Responder {

    /// public abstract com.johnholdsworth.swiftbindings.SwiftAdapterBinding$Responder com.johnholdsworth.swiftbindings.SwiftBluetoothScannerActivityBinding$Responder.getAdapter()

    func getAdapter() -> SwiftAdapterBinding_Responder!

}


open class SwiftBluetoothScannerActivityBinding_ResponderForward: SwiftActivityBinding_ResponderForward, SwiftBluetoothScannerActivityBinding_Responder {

    private static var SwiftBluetoothScannerActivityBinding_ResponderJNIClass: jclass?

    /// public abstract com.johnholdsworth.swiftbindings.SwiftAdapterBinding$Responder com.johnholdsworth.swiftbindings.SwiftBluetoothScannerActivityBinding$Responder.getAdapter()

    private static var getAdapter_MethodID_2: jmethodID?

    open func getAdapter() -> SwiftAdapterBinding_Responder! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getAdapter", methodSig: "()Lcom/johnholdsworth/swiftbindings/SwiftAdapterBinding$Responder;", methodCache: &SwiftBluetoothScannerActivityBinding_ResponderForward.getAdapter_MethodID_2, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? SwiftAdapterBinding_ResponderForward( javaObject: __return ) : nil
    }


}

