
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral ///

public protocol SwiftBluetoothBinding_Peripheral: JavaProtocol {

}


open class SwiftBluetoothBinding_PeripheralForward: JNIObjectForward, SwiftBluetoothBinding_Peripheral {

    private static var SwiftBluetoothBinding_PeripheralJNIClass: jclass?

}

