
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Responder ///

public protocol SwiftBluetoothBinding_Responder: JavaProtocol {

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Responder.startScan(com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings,com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanCallback)

    func startScan( settings: SwiftBluetoothBinding_ScanSettings?, callback: SwiftBluetoothBinding_ScanCallback? )

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Responder.stopScan()

    func stopScan()

}


open class SwiftBluetoothBinding_ResponderForward: JNIObjectForward, SwiftBluetoothBinding_Responder {

    private static var SwiftBluetoothBinding_ResponderJNIClass: jclass?

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Responder.startScan(com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings,com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanCallback)

    private static var startScan_MethodID_3: jmethodID?

    open func startScan( settings: SwiftBluetoothBinding_ScanSettings?, callback: SwiftBluetoothBinding_ScanCallback? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = JNIType.toJava( value: settings, locals: &__locals )
        __args[1] = JNIType.toJava( value: callback, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "startScan", methodSig: "(Lcom/johnholdsworth/swiftbindings/SwiftBluetoothBinding$ScanSettings;Lcom/johnholdsworth/swiftbindings/SwiftBluetoothBinding$ScanCallback;)V", methodCache: &SwiftBluetoothBinding_ResponderForward.startScan_MethodID_3, args: &__args, locals: &__locals )
    }

    open func startScan( _ _settings: SwiftBluetoothBinding_ScanSettings?, _ _callback: SwiftBluetoothBinding_ScanCallback? ) {
        startScan( settings: _settings, callback: _callback )
    }

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Responder.stopScan()

    private static var stopScan_MethodID_4: jmethodID?

    open func stopScan() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "stopScan", methodSig: "()V", methodCache: &SwiftBluetoothBinding_ResponderForward.stopScan_MethodID_4, args: &__args, locals: &__locals )
    }


}

