
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftListViewBinding ///

public protocol SwiftListViewBinding: JavaProtocol {

}


open class SwiftListViewBindingForward: JNIObjectForward, SwiftListViewBinding {

    private static var SwiftListViewBindingJNIClass: jclass?

}

