
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftActivityBinding ///

public protocol SwiftActivityBinding: JavaProtocol {

}


open class SwiftActivityBindingForward: JNIObjectForward, SwiftActivityBinding {

    private static var SwiftActivityBindingJNIClass: jclass?

}

