
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothScannerActivityBinding ///

public protocol SwiftBluetoothScannerActivityBinding: SwiftActivityBinding {

}


open class SwiftBluetoothScannerActivityBindingForward: SwiftActivityBindingForward, SwiftBluetoothScannerActivityBinding {

    private static var SwiftBluetoothScannerActivityBindingJNIClass: jclass?

}

