
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothScannerActivityBinding$DeviceCell ///

public protocol SwiftBluetoothScannerActivityBinding_DeviceCell: SwiftAdapterBinding_Cell {

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothScannerActivityBinding$DeviceCell.setTitle(java.lang.String)

    func setTitle( title: String? )

}


open class SwiftBluetoothScannerActivityBinding_DeviceCellForward: SwiftAdapterBinding_CellForward, SwiftBluetoothScannerActivityBinding_DeviceCell {

    private static var SwiftBluetoothScannerActivityBinding_DeviceCellJNIClass: jclass?

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothScannerActivityBinding$DeviceCell.setTitle(java.lang.String)

    private static var setTitle_MethodID_2: jmethodID?

    open func setTitle( title: String? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: title, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setTitle", methodSig: "(Ljava/lang/String;)V", methodCache: &SwiftBluetoothScannerActivityBinding_DeviceCellForward.setTitle_MethodID_2, args: &__args, locals: &__locals )
    }

    open func setTitle( _ _title: String? ) {
        setTitle( title: _title )
    }

}

