
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$BluetoothDevice ///

public protocol SwiftBluetoothBinding_BluetoothDevice: JavaProtocol {

    /// public abstract com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral$Responder com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$BluetoothDevice.connect(int,com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral$Listener)

    func connect( transport: Int, listener: SwiftBluetoothBinding_Peripheral_Listener? ) -> SwiftBluetoothBinding_Peripheral_Responder!

    /// public abstract java.lang.String com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$BluetoothDevice.getAddress()

    func getAddress() -> String!

    /// public abstract int com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$BluetoothDevice.getDeviceClass()

    func getDeviceClass() -> Int

    /// public abstract java.lang.String com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$BluetoothDevice.getName()

    func getName() -> String!

    /// public abstract int com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$BluetoothDevice.getType()

    func getType() -> Int

}


open class SwiftBluetoothBinding_BluetoothDeviceForward: JNIObjectForward, SwiftBluetoothBinding_BluetoothDevice {

    private static var SwiftBluetoothBinding_BluetoothDeviceJNIClass: jclass?

    /// public abstract com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral$Responder com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$BluetoothDevice.connect(int,com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$Peripheral$Listener)

    private static var connect_MethodID_6: jmethodID?

    open func connect( transport: Int, listener: SwiftBluetoothBinding_Peripheral_Listener? ) -> SwiftBluetoothBinding_Peripheral_Responder! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = jvalue( i: jint(transport) )
        __args[1] = JNIType.toJava( value: listener, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "connect", methodSig: "(ILcom/johnholdsworth/swiftbindings/SwiftBluetoothBinding$Peripheral$Listener;)Lcom/johnholdsworth/swiftbindings/SwiftBluetoothBinding$Peripheral$Responder;", methodCache: &SwiftBluetoothBinding_BluetoothDeviceForward.connect_MethodID_6, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? SwiftBluetoothBinding_Peripheral_ResponderForward( javaObject: __return ) : nil
    }

    open func connect( _ _transport: Int, _ _listener: SwiftBluetoothBinding_Peripheral_Listener? ) -> SwiftBluetoothBinding_Peripheral_Responder! {
        return connect( transport: _transport, listener: _listener )
    }

    /// public abstract java.lang.String com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$BluetoothDevice.getAddress()

    private static var getAddress_MethodID_7: jmethodID?

    open func getAddress() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getAddress", methodSig: "()Ljava/lang/String;", methodCache: &SwiftBluetoothBinding_BluetoothDeviceForward.getAddress_MethodID_7, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


    /// public abstract int com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$BluetoothDevice.getDeviceClass()

    private static var getDeviceClass_MethodID_8: jmethodID?

    open func getDeviceClass() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "getDeviceClass", methodSig: "()I", methodCache: &SwiftBluetoothBinding_BluetoothDeviceForward.getDeviceClass_MethodID_8, args: &__args, locals: &__locals )
        return Int(__return)
    }


    /// public abstract java.lang.String com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$BluetoothDevice.getName()

    private static var getName_MethodID_9: jmethodID?

    open func getName() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getName", methodSig: "()Ljava/lang/String;", methodCache: &SwiftBluetoothBinding_BluetoothDeviceForward.getName_MethodID_9, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


    /// public abstract int com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$BluetoothDevice.getType()

    private static var getType_MethodID_10: jmethodID?

    open func getType() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "getType", methodSig: "()I", methodCache: &SwiftBluetoothBinding_BluetoothDeviceForward.getType_MethodID_10, args: &__args, locals: &__locals )
        return Int(__return)
    }


}

