
import java_swift
import java_util

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanCallback ///

public protocol SwiftBluetoothBinding_ScanCallback: JavaProtocol {

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanCallback.onBatchScanResults(java.util.List)

    func onBatchScanResults( results: java_util.List? )

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanCallback.onScanFailed(int)

    func onScanFailed( errorCode: Int )

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanCallback.onScanResult(int,com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanResult)

    func onScanResult( callbackType: Int, result: SwiftBluetoothBinding_ScanResult? )

}


open class SwiftBluetoothBinding_ScanCallbackForward: JNIObjectForward, SwiftBluetoothBinding_ScanCallback {

    private static var SwiftBluetoothBinding_ScanCallbackJNIClass: jclass?

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanCallback.onBatchScanResults(java.util.List)

    private static var onBatchScanResults_MethodID_4: jmethodID?

    open func onBatchScanResults( results: java_util.List? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: results, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "onBatchScanResults", methodSig: "(Ljava/util/List;)V", methodCache: &SwiftBluetoothBinding_ScanCallbackForward.onBatchScanResults_MethodID_4, args: &__args, locals: &__locals )
    }

    open func onBatchScanResults( _ _results: java_util.List? ) {
        onBatchScanResults( results: _results )
    }

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanCallback.onScanFailed(int)

    private static var onScanFailed_MethodID_5: jmethodID?

    open func onScanFailed( errorCode: Int ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = jvalue( i: jint(errorCode) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "onScanFailed", methodSig: "(I)V", methodCache: &SwiftBluetoothBinding_ScanCallbackForward.onScanFailed_MethodID_5, args: &__args, locals: &__locals )
    }

    open func onScanFailed( _ _errorCode: Int ) {
        onScanFailed( errorCode: _errorCode )
    }

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanCallback.onScanResult(int,com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanResult)

    private static var onScanResult_MethodID_6: jmethodID?

    open func onScanResult( callbackType: Int, result: SwiftBluetoothBinding_ScanResult? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = jvalue( i: jint(callbackType) )
        __args[1] = JNIType.toJava( value: result, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "onScanResult", methodSig: "(ILcom/johnholdsworth/swiftbindings/SwiftBluetoothBinding$ScanResult;)V", methodCache: &SwiftBluetoothBinding_ScanCallbackForward.onScanResult_MethodID_6, args: &__args, locals: &__locals )
    }

    open func onScanResult( _ _callbackType: Int, _ _result: SwiftBluetoothBinding_ScanResult? ) {
        onScanResult( callbackType: _callbackType, result: _result )
    }

}

