
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings ///

public protocol SwiftBluetoothBinding_ScanSettings: JavaProtocol {

    /// public abstract int com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings.getCallbackType()

    func getCallbackType() -> Int

    /// public abstract int com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings.getMatchMode()

    func getMatchMode() -> Int

    /// public abstract int com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings.getNumberOfMatchesPerFilter()

    func getNumberOfMatchesPerFilter() -> Int

    /// public abstract long com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings.getReportDelayMiliseconds()

    func getReportDelayMiliseconds() -> Int64

    /// public abstract int com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings.getScanMode()

    func getScanMode() -> Int

    /// public abstract int com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings.getScanResultType()

    func getScanResultType() -> Int

}


open class SwiftBluetoothBinding_ScanSettingsForward: JNIObjectForward, SwiftBluetoothBinding_ScanSettings {

    private static var SwiftBluetoothBinding_ScanSettingsJNIClass: jclass?

    /// public abstract int com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings.getCallbackType()

    private static var getCallbackType_MethodID_7: jmethodID?

    open func getCallbackType() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "getCallbackType", methodSig: "()I", methodCache: &SwiftBluetoothBinding_ScanSettingsForward.getCallbackType_MethodID_7, args: &__args, locals: &__locals )
        return Int(__return)
    }


    /// public abstract int com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings.getMatchMode()

    private static var getMatchMode_MethodID_8: jmethodID?

    open func getMatchMode() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "getMatchMode", methodSig: "()I", methodCache: &SwiftBluetoothBinding_ScanSettingsForward.getMatchMode_MethodID_8, args: &__args, locals: &__locals )
        return Int(__return)
    }


    /// public abstract int com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings.getNumberOfMatchesPerFilter()

    private static var getNumberOfMatchesPerFilter_MethodID_9: jmethodID?

    open func getNumberOfMatchesPerFilter() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "getNumberOfMatchesPerFilter", methodSig: "()I", methodCache: &SwiftBluetoothBinding_ScanSettingsForward.getNumberOfMatchesPerFilter_MethodID_9, args: &__args, locals: &__locals )
        return Int(__return)
    }


    /// public abstract long com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings.getReportDelayMiliseconds()

    private static var getReportDelayMiliseconds_MethodID_10: jmethodID?

    open func getReportDelayMiliseconds() -> Int64 {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallLongMethod( object: javaObject, methodName: "getReportDelayMiliseconds", methodSig: "()J", methodCache: &SwiftBluetoothBinding_ScanSettingsForward.getReportDelayMiliseconds_MethodID_10, args: &__args, locals: &__locals )
        return __return
    }


    /// public abstract int com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings.getScanMode()

    private static var getScanMode_MethodID_11: jmethodID?

    open func getScanMode() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "getScanMode", methodSig: "()I", methodCache: &SwiftBluetoothBinding_ScanSettingsForward.getScanMode_MethodID_11, args: &__args, locals: &__locals )
        return Int(__return)
    }


    /// public abstract int com.johnholdsworth.swiftbindings.SwiftBluetoothBinding$ScanSettings.getScanResultType()

    private static var getScanResultType_MethodID_12: jmethodID?

    open func getScanResultType() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "getScanResultType", methodSig: "()I", methodCache: &SwiftBluetoothBinding_ScanSettingsForward.getScanResultType_MethodID_12, args: &__args, locals: &__locals )
        return Int(__return)
    }


}

