
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothBinding ///

public protocol SwiftBluetoothBinding: JavaProtocol {

}


open class SwiftBluetoothBindingForward: JNIObjectForward, SwiftBluetoothBinding {

    private static var SwiftBluetoothBindingJNIClass: jclass?

}

